README.md
install-dat-release.sh
install-release.sh

It has been determined to be basically correct.

feat: Branch merge

---

README.md
install-dat-release.sh
install-release.sh

This time, mainly to explain the problem of insufficient rights when using the certificate.

feat: Description of permissions

---

README.md

style: Wiki special classification

---

install-release.sh

1. Resolve incorrect matching issues.
issue #29

fix: Changed from pgrep to pidof

---

install-release.sh

1. Modify MACHINE.
2. Add riscv64 for MACHINE.

fix: issue #33

---

install-dat-release.sh
install-release.sh

1. $DAT_PATH can be modified to /usr/local/share/v2ray/ .
2. $JSON_PATH can be modified to /etc/v2ray/ .
3. However, after modification, you need to modify the unit file yourself.
issue #17

feat: Add variables to modify the installation path

---

README.md

1. Migrate from the old script to this.
2. Move .dat files from lib directory to share directory.
3. To use the VLESS protocol.
issue #38

feat: Add new Wiki content

---

README.md
install-dat-release.sh
install-release.sh
systemd/system/v2ray.service
systemd/system/v2ray@.service

1. Move the .dat file from the lib directory to the share directory.
issue #17

fix: A wrong installation path

---

README.md
install-release.sh

1. Now, the initialization of the Log file is normal.
2. And, some new related outputs have been added.

fix: Missing Log Source

---

install-release.sh

杞人忧天中……
Request reviewer @dctxmei

优化 bash 脚本中的命令用法。

---

install-release.sh

没有合法的 UA GitHub会拒绝链接导致安装或者更新失败，提示：  
```
curl: (7) Failed to connect to api.github.com port 443: Connection refused
error: Failed to get release list, please check your network.
```

add user-agent

---

install-release.sh

bug fix for $114

---

install-release.sh

add support for archlinux package managers

---

install-dat-release.sh
install-release.sh

Show download progress; Retry when transient error occurred.

---

install-dat-release.sh
install-release.sh

Reverts v2fly/fhs-install-v2ray#131

Revert "Show download progress; Retry when transient error occurred."

---

install-release.sh

Refer: https://manpages.ubuntu.com/manpages/focal/en/man3/sd_booted.3.html

Introduce a more convenient way to detect systemd

---

install-release.sh

1，apt的正确用法是 apt [选项] 命令 ，运行apt命令即可查看
2，apt purge -y --auto-remove 相当于执行了一遍 apt autoremove，有一些依赖虽然不是自动安装的，但是可能影响用户编译软件的运行，应该由用户自行决定是否执行

Place options ahead of command

---

README.md
README.zh-Hans-CN.md

This closes #67. 
NOTE: Please squash.

Finishing off #67

---

install-release.sh

Match only whole word `v2ray` in systemd unit files.

---

.github/workflows/sh-checker.yml
install-release.sh

Test script in Ubuntu 16.04 so as to be compatible with Linux distros released in the last 4 yrs.

Revert "Replace `unzip` with `bsdtar`"

---

install-release.sh

Modify exit code number

---

install-dat-release.sh
install-release.sh

Revert "Revert "Add root uid judgment before running""

---

install-dat-release.sh
install-release.sh

1. Change Shebang from absolute path to logical path, which can adapt to
more situations.

fix: Shebang content

---

install-release.sh

supress error message "rm: cannot remove '/etc/systemd/system/v2ray.service.d/10-donot_touch_multi_conf.conf': No such file or directory"

supress error output
